[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-illuminos.json"

[target.x86_64-unknown-none]
runner = "bootimage runner"